services:
  - type: web
    name: dental-clinic
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dental_clinic.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
    postdeploy: |
      echo "Running migrations and collectstatic"
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
